[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/compmec/beam1D/blob/main/examples/cantilever.ipynb)

# Cantilever with end load

Let's suppose that we have a bar with

* Lenght $L$
* Elasticity $E$
* Poisson $\nu$
* Diameter $d$

And it's tracted with a force $P$, as shown in the figure

With the Euler-Bernoulli Beam, we will have

$$
N(x) = 0
$$
$$
V(x) = -P
$$
$$
M(x) = P(L-x)
$$

Our solution is only

$$
w(x) = \dfrac{PL^{3}}{3EI} \cdot \left[\dfrac{3}{2}\left(\dfrac{x}{L}\right)^2 - \dfrac{1}{2}\left(\dfrac{x}{L}\right)^{3}\right] 
$$

For a circular section of diameter $d$, we have

$$
I = \dfrac{\pi d^4}{64}
$$

Therefore

$$
w(x) = \dfrac{64PL^{3}}{3\pi Ed^4} \cdot \left[\dfrac{3}{2}\left(\dfrac{x}{L}\right)^2 - \dfrac{1}{2}\left(\dfrac{x}{L}\right)^{3}\right] 
$$

And the rotation is

$$
\theta_{z} = \dfrac{dw}{dx} = \dfrac{64PL^2}{3\pi Ed^4}\left[3\left(\dfrac{x}{L}\right) - \dfrac{3}{2}\left(\dfrac{x}{L}\right)^2\right]
$$

Now, let's go to the code

# Implementation

The initial values

In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True) # To have a clean print
L = 1
E = 4/np.pi
nu = 0.0  # This value doesn't matter to the final answer, but it's needed
d = 2
P = 4

We create the material we will use

In [2]:
from material import Isotropic
steel = Isotropic(E=E, nu=nu)

We create our section

In [3]:
from section import Circle
circle = Circle(R=d/2, nu=nu)

We create the beam

In [4]:
from beam import EulerBernoulli
A = (0, 0, 0)
B = (L, 0, 0)
bar = EulerBernoulli(A, B)
bar.material = steel
bar.section = circle

We add the displacement vector ```U``` and the force ```F```

The values of ```U``` are

$$
U =
\begin{bmatrix}
u_{1x} & u_{1y} & u_{1z} & \theta_{1x} & \theta_{1y} & \theta_{1z} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
u_{ix} & u_{iy} & u_{iz} & \theta_{ix} & \theta_{iy} & \theta_{2z} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
u_{nx} & u_{ny} & u_{nz} & \theta_{nx} & \theta_{ny} & \theta_{nz} \\
\end{bmatrix}
$$



And the values of ```F``` are

$$
F =
\begin{bmatrix}
F_{1x} & F_{1y} & F_{1z} & M_{1x} & M_{1y} & M_{1z} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
F_{ix} & F_{iy} & F_{iz} & M_{ix} & M_{iy} & M_{2z} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
F_{nx} & F_{ny} & F_{nz} & M_{nx} & M_{ny} & M_{nz} \\
\end{bmatrix}
$$

So, ```U[i]``` means the displacement (and rotation) of the point ```i```, and the ```F[i]``` is the force applied in the node ```i```

In [5]:
n = 2  # number of points
U = np.empty((n, 6), dtype="object")
F = np.zeros((n, 6))

We add the boundary conditions. 

For that, we only know that at point $A$ (index ```0```), $u_{x}$ is fixed.

So, ```U``` is like

$$
U
= \begin{bmatrix}
0 & 0 & u_{Az} & \theta_{Ax} & \theta_{Ay} & 0 \\
u_{Bx} & u_{By} & u_{Bz} & \theta_{Bx} & \theta_{By} & \theta_{Bz} \\ 
\end{bmatrix}
$$

In [6]:
U[0, 0] = 0  # At point A, ux = 0
U[0, 1] = 0  # At point A, uy = 0
U[0, 5] = 0  # At point A, theta_z = 0
print("U = ")
print(U)

U = 
[[0 0 None None None 0]
 [None None None None None None]]


We add the force at the point $B$.

For that, we know that at point $B$ (index ```1```), $F_{x} = P$.

So, ```F``` is like

$$
F =
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 \\
0 & P & 0 & 0 & 0 & 0
\end{bmatrix}
$$

In [7]:
F[1, 1] = P  # At point B, Fx = P
print("F = ")
print(F)

F = 
[[0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0.]]


We get the stiffness matrix $K$.

The matrix is given by

$$
K_{11} = 
\begin{bmatrix}
\frac{EA_x}{L} & 0 & 0 & 0 & 0 & 0 \\
0 & \frac{12EI_{z}}{L^3} & 0 & 0 & 0 & \frac{6EI_{z}}{L^2} \\
0 & 0 & \frac{12EI_{y}}{L^3} &  0 & \frac{-6EI_{y}}{L^2} \\
0 & 0 & 0 & \frac{GJ}{L} & 0 & 0 \\
0 & 0 & \frac{-6EI_{y}}{L^2} & 0 & \frac{4EI_{y}}{L} & 0 \\
0 & \frac{6EI_{z}}{L^2}& 0 & 0 & 0 & \frac{4EI_{z}}{L} 
\end{bmatrix}
$$

$$
K_{12} = 
\begin{bmatrix}
\frac{-EA_x}{L} & 0 & 0 & 0 & 0 & 0 \\
0 & \frac{-12EI_{z}}{L^3} & 0 & 0 & 0 & \frac{6EI_{z}}{L^2} \\
0 & 0 & \frac{-12EI_{y}}{L^3} &  0 & \frac{-6EI_{y}}{L^2} \\
0 & 0 & 0 & \frac{-GJ}{L} & 0 & 0 \\
0 & 0 & \frac{6EI_{y}}{L^2} & 0 & \frac{2EI_{y}}{L} & 0 \\
0 & \frac{-6EI_{z}}{L^2}& 0 & 0 & 0 & \frac{2EI_{z}}{L} 
\end{bmatrix}
$$

$$
K_{22} = 
\begin{bmatrix}
\frac{EA_x}{L} & 0 & 0 & 0 & 0 & 0 \\
0 & \frac{12EI_{z}}{L^3} & 0 & 0 & 0 & \frac{-6EI_{z}}{L^2} \\
0 & 0 & \frac{12EI_{y}}{L^3} &  0 & \frac{6EI_{y}}{L^2} \\
0 & 0 & 0 & \frac{GJ}{L} & 0 & 0 \\
0 & 0 & \frac{6EI_{y}}{L^2} & 0 & \frac{4EI_{y}}{L} & 0 \\
0 & \frac{-6EI_{z}}{L^2}& 0 & 0 & 0 & \frac{4EI_{z}}{L} 
\end{bmatrix}
$$

$$
K = 
\begin{bmatrix}
K_{11} & K_{12} \\
K_{12}^T & K_{22}
\end{bmatrix}
$$

For exemple, with the values of

$$
L = 1; \ \ \ \ \ \ E = \dfrac{4}{\pi}; \ \ \ \ \ \ \nu = 0 ; \ \ \ \ \ \ d = 2
$$

We have the matrix


$$
K = 
\begin{bmatrix}
4 & & & & & & -4 & & & & & \\
& 12 & & & & 6 & & -12 &  & & & 6 \\
& & 12 & & -6 & & & & -12 & & -6 & \\
& & & 1 & & & & & & -1 & & \\
& & -6 & & 4 & & & & 6 & & 2 & \\
& 6 & & & & 4 & & -6 &  & & & 2 \\
-4 & & & & & & 4 & & & & & \\
& -12 & & & & -6 & & 12 &  & & & -6 \\
& & -12 & & 6 & & & & 12 & & 6 & \\
& & & -1 & & & & & & 1 & & \\
& & -6 & & 2 & & & & 6 & & 4 & \\
& 6 & & & & 2 & & -6 &  & & & 4 \\
\end{bmatrix}
$$

In [8]:
K = bar.stiffness_matrix()
print("K = ")
print(K.reshape(12, 12))

K = 
[[  4.   0.   0.   0.   0.   0.  -4.   0.   0.   0.   0.   0.]
 [  0.  12.   0.   0.   0.   6.   0. -12.   0.   0.   0.   6.]
 [  0.   0.  12.   0.  -6.   0.   0.   0. -12.   0.  -6.   0.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   0.  -1.   0.   0.]
 [  0.   0.  -6.   0.   4.   0.   0.   0.   6.   0.   2.   0.]
 [  0.   6.   0.   0.   0.   4.   0.  -6.   0.   0.   0.   2.]
 [ -4.   0.   0.   0.   0.   0.   4.   0.   0.   0.   0.   0.]
 [  0. -12.   0.   0.   0.  -6.   0.  12.   0.   0.   0.  -6.]
 [  0.   0. -12.   0.   6.   0.   0.   0.  12.   0.   6.   0.]
 [  0.   0.   0.  -1.   0.   0.   0.   0.   0.   1.   0.   0.]
 [  0.   0.  -6.   0.   2.   0.   0.   0.   6.   0.   4.   0.]
 [  0.   6.   0.   0.   0.   2.   0.  -6.   0.   0.   0.   4.]]


Now we solve:

In [9]:
from solver import solve
U, F = solve(K, F, U)
U = np.array(U, dtype="float64")
print("U = ")
print(U)
print("F = ")
print(F)

U = 
[[ 0.     0.     0.    -0.     0.     0.   ]
 [ 0.     1.333 -0.    -0.     0.     2.   ]]
F = 
[[-0. -4.  0.  0.  0. -4.]
 [ 0.  4.  0.  0.  0.  0.]]


The expected value of the equation 

$$
w(x) = \dfrac{64PL^{3}}{3\pi Ed^4} \cdot \left[\dfrac{3}{2}\left(\dfrac{x}{L}\right)^2 - \dfrac{1}{2}\left(\dfrac{x}{L}\right)^{3}\right] 
$$

at $x = L$ and with the given data, gives us 

$$
w(L) = \dfrac{64PL^3}{3\pi Ed^4} = \dfrac{64 \cdot 4 \cdot 1^{3}}{3 \pi \cdot \dfrac{4}{\pi} \cdot 2^{4}} = \dfrac{4}{3} \approx 1.333
$$



The rotation $\theta_{z}(x)$ is given by


$$
\theta_{z}(x) = \dfrac{64PL^2}{3\pi Ed^4}\left[3\left(\dfrac{x}{L}\right) - \dfrac{3}{2}\left(\dfrac{x}{L}\right)^2\right]
$$

at $x = L$ with the given data

$$
\theta_{z}(L) = \dfrac{64 \cdot 4 \cdot 1^2}{3\pi \cdot \dfrac{4}{\pi} \cdot 2^4}\left[3 - \dfrac{3}{2}\right] = 2
$$